// The printable flyer: a QR to the site plus the class code, in English and
// Spanish on one sheet.
//
// The QR is generated by engine/qr.js, not fetched from an image API. A flyer
// is the one artefact a teacher prints once and hands to sixty families, so a
// third-party URL baked into it would outlive any decision to stop using that
// service -- and would tell that service which school printed it.

import { qrSvg } from './engine/qr.js';
import { el, mount } from './engine/dom.js';
import config from './config.js';

const COPY = {
  en: {
    heading: 'Math practice at home',
    lead: 'Five minutes a day. Free, no account, no app to install.',
    classLabel: 'Class code',
    steps: [
      'Point your phone camera at the square code.',
      'Tap the link that appears.',
      'Pick a picture and a nickname — no real names needed.',
      'Enter the class code above and your child’s list number.',
    ],
    note: 'Works without internet after the first visit. Nothing about your child is ever sent anywhere.',
  },
  es: {
    heading: 'Practica de matematicas en casa',
    lead: 'Cinco minutos al dia. Gratis, sin cuenta, sin aplicacion que instalar.',
    classLabel: 'Codigo de clase',
    steps: [
      'Apunte la camara de su telefono al codigo cuadrado.',
      'Toque el enlace que aparece.',
      'Escoja un dibujo y un apodo: no hace falta el nombre real.',
      'Escriba el codigo de clase de arriba y el numero de lista de su hijo.',
    ],
    note: 'Funciona sin internet despues de la primera visita. Nunca se envia nada sobre su hijo a ningun lado.',
  },
};

const codeSelect = document.getElementById('class-code');
const urlInput = document.getElementById('site-url');

function defaultSiteUrl() {
  // Wherever this page is served from, minus the filename.
  const url = new URL('./', location.href);
  return url.href;
}

function flyer(lang, classCode, siteUrl) {
  const copy = COPY[lang];
  // The class code rides in the URL so the family lands with it already chosen.
  const target = `${siteUrl}${siteUrl.includes('?') ? '&' : '?'}class=${encodeURIComponent(classCode)}`;

  return el('section', { class: 'flyer', lang },
    el('h2', { text: copy.heading }),
    el('p', { class: 'muted', style: 'margin:0', text: copy.lead }),
    el('div', { class: 'flyer__qr' }, qrSvg(target, { size: 210, label: `QR: ${target}` })),
    el('p', { class: 'flyer__url', text: siteUrl.replace(/^https?:\/\//, '').replace(/\/$/, '') }),
    el('p', { style: 'margin:0' },
      el('span', { class: 'muted', text: `${copy.classLabel}: ` }),
    ),
    el('span', { class: 'flyer__class', text: classCode }),
    el('ol', { class: 'flyer__steps' }, copy.steps.map((s) => el('li', { text: s }))),
    el('p', { class: 'muted', style: 'margin-top:12px', text: copy.note }),
    el('p', { class: 'muted', style: 'margin:4px 0 0', text: `${config.TEACHER_NAME} · ${config.SCHOOL_NAME}` }),
  );
}

function render() {
  const classCode = codeSelect.value || config.CLASS_CODES[0] || '6A';
  const siteUrl = urlInput.value.trim() || defaultSiteUrl();
  mount(document.getElementById('main'),
    flyer('en', classCode, siteUrl),
    flyer('es', classCode, siteUrl),
  );
}

function boot() {
  for (const code of config.CLASS_CODES) {
    codeSelect.append(el('option', { value: code, text: code }));
  }
  urlInput.value = defaultSiteUrl();
  codeSelect.addEventListener('change', render);
  urlInput.addEventListener('input', render);
  document.getElementById('print').addEventListener('click', () => window.print());
  render();
}

boot();
