// Regenerates tests/vectors.json -- the contract between engine/progressCode.js
// and DECODE_PROGRESS() in setup/progress-form.gs.
//
// Run this ONLY when the bit layout changes on purpose, and update the Apps
// Script decoder in the same commit.
import { writeFileSync } from 'node:fs';
import { encodeProgress } from '../../engine/progressCode.js';

const payloads = [
  {
    name: 'typical week with a badge',
    payload: { classCode: '6A', studentNumber: 14, week: 3, daysPractised: 4,
      accuracy: 0.92, medianMs: 2400, badge: true,
      missed: ['mult:7x8', 'div:42/6', 'longdiv:372/4'] },
  },
  {
    name: 'no badge, low accuracy, two days',
    payload: { classCode: '6B', studentNumber: 7, week: 5, daysPractised: 2,
      accuracy: 0.55, medianMs: 6100, badge: false, missed: ['div:56/7'] },
  },
  {
    name: 'perfect week, no misses',
    payload: { classCode: 'MRN6', studentNumber: 1, week: 8, daysPractised: 5,
      accuracy: 1, medianMs: 1500, badge: true, missed: [] },
  },
  {
    name: 'all fields at their minimum',
    payload: { classCode: '', studentNumber: 0, week: 1, daysPractised: 0,
      accuracy: 0, medianMs: 0, badge: false, missed: [] },
  },
  {
    name: 'all fields at their maximum',
    payload: { classCode: 'ZZZZ', studentNumber: 255, week: 63, daysPractised: 7,
      accuracy: 1, medianMs: 102300, badge: true,
      missed: ['longdiv:16383/127', 'xmult:16383x127', 'xdiv:16383/127'] },
  },
  {
    name: 'extended facts week',
    payload: { classCode: '601', studentNumber: 22, week: 6, daysPractised: 3,
      accuracy: 0.85, medianMs: 3000, badge: false,
      missed: ['xmult:40x7', 'xdiv:3600/9'] },
  },
];

const out = {
  $comment:
    'Generated by tests/tools/make-vectors.mjs. These codes pin the wire format. ' +
    'engine/progressCode.js and DECODE_PROGRESS() in setup/progress-form.gs must ' +
    'both reproduce every one of them.',
  version: 1,
  vectors: payloads.map((p) => ({ ...p, code: encodeProgress(p.payload) })),
};

writeFileSync(
  new URL('../vectors.json', import.meta.url),
  JSON.stringify(out, null, 2) + '\n',
);
console.log(`wrote ${out.vectors.length} vectors`);
for (const v of out.vectors) console.log(`  ${v.code}  ${v.name}`);
